name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Checkout SynoCommunity Source and Docker Image
        run: |
          git clone https://github.com/SynoCommunity/spksrc.git /home/runner/work/spksrc
          docker pull ghcr.io/synocommunity/spksrc
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /home/runner/work/spksrc/distrib
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-spksrc-primes
      - name: Build Binary
        run: |
          workdir=$(pwd)
          (cd $workdir/src/cmd && go build -ldflags="-s -w" -o ../bin/spm-exec spm-exec.go)
          upx -9 $workdir/src/bin/spm-exec
      - name: Build Package
        run: |
          workdir=$(pwd)
          docker run -v /home/runner/work/spksrc:/spksrc \
              -v $workdir:/spksrc/spk/simplepermissionmanager \
              -v $workdir/packages:/spksrc/packages \
              -w /spksrc/spk/simplepermissionmanager \
              ghcr.io/synocommunity/spksrc \
              make arch-x64-7.2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: packages/*.spk
      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            /home/runner/work/spksrc/distrib
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
